### ISSUE TITLE
Add a screenshot to the README

### ISSUE THREAD

**Issue by inputsh** [Dotnaught/vulture-feeds#1]
So I just skimmed over both the article on The Register and the README file and found a single, low quality photo in the screenshot: 

![](https://regmedia.co.uk/2018/02/22/vulture_feeds.jpg)

Since this image is really low quality, and since the article in question doesn't appear to be linked from the repo itself, I propose a higher quality image in the README.

I know that good design isn't the main point of this repo, but few people will be interested in installing a desktop app that they can't even see the interface of before building it.

**Comment by Dotnaught** [comment]
<img alt="vulture-feeds-screenshot" src="https://user-images.githubusercontent.com/429084/36622694-90e4dd1a-18b3-11e8-9076-e1e344f825ab.png" style="max-width:100%;">
